name: iban_form_field_updated
description: An IBAN form which deals with spacing and country specific rules.
version: 0.0.1
homepage: https://github.com/emrhnzngn/iban_form_field_updated

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  iban: ^1.0.1
  flutter:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  test: ^1.6.0
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

